# Generated by Django 2.2 on 2019-04-07 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20190407_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='Num',
            field=models.CharField(default='11r', max_length=10),
            preserve_default=False,
        ),
    ]
